export const ROUTES = {
  home: "/",
  about: "/about-us",
  legal: "/legal",
  contact: "/contact-us",
  forex_trading: "/trading/forex",
  indices_trading: "/trading/indices",
  crypto_trading: "/trading/crypto",
  stocks_trading: "/trading/stocks",
  commodities_trading: "/trading/commodities",
  platforms_desktop: "/platforms/desktop",
  platforms_mobile: "/platforms/mobile",
  platforms_web: "/platforms/web",
  accounts_comparison: "/accounts/comparison",
  accounts_live: "/accounts/live",
  accounts_demo: "/accounts/demo",
};
